### ISSUE TITLE
Missing Plugin Exception

### ISSUE THREAD

**Issue by bhavindhodia** [applicazza/whatsapp_stickers#1]
Whenever I launch the app on my android phone an try to add the stickers pack I run into Missing Plugin Exception error.I googled for the reason and tried `flutter clean` command but the issue still occurred 

![Annotation 2019-12-20 180902](https://user-images.githubusercontent.com/33523216/71255410-d883de80-2353-11ea-88fd-724256688808.png)

**Comment by applicazza** [comment]
Kindly share your ```pubspec.yaml```

**Comment by applicazza** [comment]
Closing for now. Feel free to reopen if needed.
