### ISSUE TITLE
Always get FILE_NOT_FOUND Exception

### ISSUE THREAD

**Issue by viztushar** [applicazza/whatsapp_stickers#3]
my sticker are stored in server so first user download stickers and i store those sticker into Application Documents Directory with help of getApplicationDocumentsDirectory() method and after that i call the " await stickerPack.sendToWhatsApp();" but always get FILE_NOT_FOUND Exception.

**Comment by wangshimeng** [comment]
I meet the same problem,have you resolved it

**Comment by wangshimeng** [comment]
@viztushar @applicazza

**Comment by 54lianxi** [comment]
@applicazza ，I meet the problem，I want to know have anyone used it successful,I hope the developer can give a detailed explanation

**Comment by applicazza** [comment]
Plugin has been updated to version 0.0.2

I have added detailed instruction in README about adding both local and remote stickers.

Closing an issue for now, feel free to reopen it if needed.
