### ISSUE TITLE
I failed to use this plugin，Is the plugin finished,Can it be used successful

### ISSUE THREAD

**Issue by 54lianxi** [applicazza/whatsapp_stickers#4]
1.Please provide a detailed instruction.
2.Is the local and dynamic usage the same?，local：Put the picture on the asset.dynamic:Download from the network.
3.no other configuration?
4.now,I tried to use assets.but failed,and no exception,dynamic,It show thats not found picture.
5.If it is not finished,please talk to me.
thanks
@applicazza

**Comment by applicazza** [comment]
Updated to version 0.0.2 and added detailed information both for local and remote assets.
