### ISSUE TITLE
 Unhandled Exception: MissingPluginException(No implementation found for method sendToWhatsApp on channel whatsapp_stickers)

### ISSUE THREAD

**Issue by sivapictuscode** [applicazza/whatsapp_stickers#6]
Hi, Nice plugin, But i always get this error only.

 Unhandled Exception: MissingPluginException(No implementation found for method sendToWhatsApp on channel whatsapp_stickers)

Even i tried all the ways flutter clean and also delete plugin and reinstall always getting same error. Can you please guide me.
my flutter version 1.17.4
plugin: whatsapp_stickers: ^0.0.2

Thanks.

**Comment by applicazza** [comment]
Currently iOS is the only support platform. 

Are you trying to use it with iOS application? If yes, by any chance you could share repository with your code?

**Comment by applicazza** [comment]
Closing for now. Feel free to reopen if needed.
